### ISSUE TITLE
Write an algorithm that calculates sum of first 10 natural numbers. (Pseduocode and Flowchart)

### ISSUE THREAD

**Issue by lA12-coder** [toowaki/yFlowGen#4]

**Comment by toowaki** [comment]
Thank you for filing an issue. 
Could you please provide some sample code to reproduce the issue and the expected behavior?

**Comment by toowaki** [comment]
The C code and its flowchart are shown below.
yFlowGen does not generate code.
You can write the code yourself, or use ChatGPT or similar to generate sample code.

![image](https://github.com/toowaki/yFlowGen/assets/26063989/7f218333-3e6a-49ca-b9cc-4ac8c2105d27)
